services:
  postgres:
    image: postgres:17.5
    restart: unless-stopped
    container_name: hono-template
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: template